### ISSUE TITLE
401 error on console "message":"App Id is missing"}

### ISSUE THREAD

**Issue by gilbertlucas46** [selfbits/selfbits-angular2-sdk#1]
Hi I'm currently following instructions in http://blog.selfbits.io/blog/tutorial/angular2/2016/11/24/dashboard-tutorial-part2-email-auth
![image](https://cloud.githubusercontent.com/assets/5719346/20888692/f23f3948-bb3a-11e6-86b0-ecc6023a78f7.png)
I'm now in the part where I need to test the connection in the register form
![image](https://cloud.githubusercontent.com/assets/5719346/20888777/38f663fc-bb3b-11e6-8848-8a1a056b35fa.png)

I'm not really sure what I did wrong.. you can check the actual page here.
http://cheapytrippy.com/dashboard/#/login

Hope to get support from you guys soon :)

**Comment by kreck** [comment]
The problem was is the missing 'sb-app-id' in the header when implementing the signUp method.

```javascript
signup(formData:auth):Observable<Response>{
    return this.http.post(
      `${this.config.BASE_URL}/api/v1/auth/signup`,
      JSON.stringify(formData),
      {headers:new Headers({'Content-Type':'application/json','sb-app-id':this.config.APP_ID,'sb-app-secret':this.config.APP_SECRET})})
  }
```

At `'sb-app-id':this.config.APP_ID` it is literally 'sb-app-id'. It is the name of the http header which is assigned the APP_ID value (that 32 digit key) from the config Object.

**Comment by gilbertlucas46** [comment]
thanks @kreck  it's working now
